---
slow_crawl: false
more_details: false
apks_pool_folder: apks
apks_pool_size_mb: 200
max_task_duration_seconds: 600
max_download_duration_seconds: 3600
mongodb:
        name: crawler_db
        address: 127.0.0.1
        port: 27017
        user: playstore_crawler
        password: alessandrodd