---
slow_crawl: false
more_details: false
apks_pool_folder: /mnt/c/Users/filib/PycharmProjects/apk_api_key_extractor/apks
apks_pool_size_mb: 2000
max_task_duration_seconds: 600
max_download_duration_seconds: 3600
mongodb:
        name: crawler_db
        address: 192.168.0.1
        port: 27017
        user: api_key_extractor
        password: alessandrodd